gText_Birch_Welcome::
	.string "Hello there! Glad to meet you!\p"
	.string "Welcome to the world of Moémon!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the Moémon PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This here is known as a “Moémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world...\l"
	.string "...is inhabited far and wide\n"
	.string "by these Moémon.\p"
	.string "For some people Moémon are pets.\p"
	.string "Others use them for battling.\p"
	.string "As for myself…\l"
	.string "I study Pokémon as a profession\n"
	.string "in the KANTO region.\p"
	.string "I'm visiting AERO at the request\n"
	.string "of an old friend.\p"
	.string "But first,\l"
	.string "tell me a little about yourself.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now tell me.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Let's begin with your name.\n"
	.string "What is it?$"

gText_Birch_SoItsPlayer::
	.string "Right...\n"
	.string "So your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}...\p"
	.string "Good to meet you.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Your very own Moémon story is\n"
	.string "about to unfold.\p"
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures with\n"
	.string "Moémon awaits!\p"
	.string "Good luck.\n"
	.string "I hope to see you again soon.\p"
	.string "$"
